package schema

import (
	"fmt"
	"os"

	"gopkg.in/yaml.v3"
)

// WriteFile writes the PluginSchema to a file in YAML format, including a header with the execution path.
// The filename specifies the output file, and resolver is used to determine the current working directory.
func (p *PluginSchema) WriteFile(filename string, callerPath string) error {
	yamlData, err := yaml.Marshal(p)
	if err != nil {
		return fmt.Errorf("failed to marshal YAML: %w", err)
	}
	// TODO: allow the header prefix to be configurable
	schemaHeader := "# yaml-language-server: $schema=https://json-schema.org/draft/2020-12/schema"
	header := fmt.Sprintf("%s\n# File generated by '%s'. DO NOT EDIT.\n", schemaHeader, callerPath)
	content := append([]byte(header), yamlData...)

	if err = os.WriteFile(filename, content, 0600); err != nil {
		return fmt.Errorf("failed to write file %s: %w", filename, err)
	}

	return nil
}
