package schema_test

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/cultureamp/terraform-buildkite-plugin/pkg/schema/schema"
	"github.com/stretchr/testify/require"
)

// UnmarshalableType simulates a type that fails YAML marshaling.
type UnmarshalableType struct{}

func (u UnmarshalableType) MarshalYAML() (interface{}, error) {
	return nil, os.ErrInvalid
}

// samplePlugin creates a sample PluginSchema for testing purposes.
func samplePlugin() schema.PluginSchema {
	return schema.PluginSchema{
		Name:        "example",
		Description: "example description",
		Author:      "example author",
		Requirements: []string{
			"requirement-1",
			"requirement-2",
		},
		Configuration: map[string]interface{}{
			"configKey": "configValue",
		},
	}
}

// TestWriteFile tests the WriteFile method of Plugingenerator.
func TestWriteFile(t *testing.T) {
	t.Run("Success", func(t *testing.T) {
		tmpDir := t.TempDir()
		outputPath := filepath.Join(tmpDir, "output.yaml")
		callerPath := "./tools/schema"

		p := samplePlugin()

		err := p.WriteFile(outputPath, callerPath)
		require.NoError(t, err)

		contents, err := os.ReadFile(outputPath)
		require.NoError(t, err)
		require.Contains(t, string(contents), "# File generated by './tools/schema'")
		require.Contains(t, string(contents), "example")
	})

	t.Run("InvalidFilename", func(t *testing.T) {
		callerPath := "./tools/schema"

		p := samplePlugin()

		err := p.WriteFile("/this/does/not/exist/output.yaml", callerPath)
		require.Error(t, err)
		require.Contains(t, err.Error(), "failed to write file")
	})

	t.Run("MarshalError", func(t *testing.T) {
		tmpDir := t.TempDir()
		outputPath := filepath.Join(tmpDir, "output.yaml")
		callerPath := "./tools/schema"

		p := schema.PluginSchema{
			Name:          "example",
			Description:   "example description",
			Author:        "example author",
			Requirements:  []string{"requirement-1", "requirement-2"},
			Configuration: map[string]interface{}{"invalid": UnmarshalableType{}},
		}

		err := p.WriteFile(outputPath, callerPath)
		require.Error(t, err)
		require.Contains(t, err.Error(), "failed to marshal YAML")
	})
}
