# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
#
# Visit https://goreleaser.com for documentation on how to customize this behavior.
version: 2

builds:
  - id: main
    main: ./cmd/plugin
    env:
      # goreleaser does not work with CGO, it could also complicate usage by users in CI/CD systems where they are
      # unable to install libraries.
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - '-s -w -extldflags "-static" -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.name={{.ProjectName}}'
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ignore: []
    binary: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
archives:
  - id: no-archive
    ids:
      - main
    formats:
      - binary
